export { default as Header } from "./header"
export { default as MainVideo } from "./mainVideo"
export { default as Work } from "./work"
export { default as ProjectCard } from "./projectCard"
export { default as About } from "./about"